# automatically generated by the FlatBuffers compiler, do not modify

# namespace: PingPong

import flatbuffers

class PlayerAction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPlayerAction(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayerAction()
        x.Init(buf, n + offset)
        return x

    # PlayerAction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayerAction
    def MoveDirection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def PlayerActionStart(builder): builder.StartObject(1)
def PlayerActionAddMoveDirection(builder, moveDirection): builder.PrependInt8Slot(0, moveDirection, 0)
def PlayerActionEnd(builder): return builder.EndObject()
