// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PingPong
{

using global::System;
using global::FlatBuffers;

public enum MoveDirection : sbyte
{
  Up = 0,
  Down = 1,
  None = 2,
};


}
